In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
import os
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [3]:
model_path = '/content/drive/MyDrive/공모전/분석/모델'
filename = os.path.join(model_path, 'tmp_checkpoint.h5')

In [4]:
def make_dataset(data, label, window_size=24):
    feature_list = []
    label_list = []
    for i in range(len(data) - window_size):
        feature_list.append(np.array(data.iloc[i:i+window_size]))
        label_list.append(np.array(label.iloc[i+window_size]))
    return np.array(feature_list), np.array(label_list)

In [5]:
df  = pd.read_csv('/content/drive/MyDrive/공모전/데이터/학습용/데이터변환2.csv')

In [6]:
data = df[['속도','지점번호','교통량', '요일', '방향', '거리', '차선수',
       '기능유형구분', '합류도로수', '제한속도', '주말 유무']]

In [116]:
c_data = data[data['지점번호']=='C-17']

In [117]:
c_data

          속도  지점번호   교통량  요일  방향    거리  차선수  기능유형구분  합류도로수  제한속도  주말 유무
96     89.00  C-17   520   2   0  1575    3       1      3    80      0
97     87.50  C-17   415   2   0  1575    3       1      3    80      0
98     89.67  C-17   373   2   0  1575    3       1      3    80      0
99     87.67  C-17   559   2   0  1575    3       1      3    80      0
100    88.58  C-17  1324   2   0  1575    3       1      3    80      0
...      ...   ...   ...  ..  ..   ...  ...     ...    ...   ...    ...
73771  31.92  C-17  2692   1   1  1138    3       1      2    80      0
73772  69.67  C-17  2669   1   1  1138    3       1      2    80      0
73773  73.75  C-17  2295   1   1  1138    3       1      2    80      0
73774  78.17  C-17  1409   1   1  1138    3       1      2    80      0
73775  83.67  C-17   903   1   1  1138    3       1      2    80      0

[15024 rows x 11 columns]

In [118]:
c0_data = c_data[c_data['방향']==0]
c1_data = c_data[c_data['방향']==1]

In [10]:
max_0 = c0_data['속도'].max()
min_0 = c0_data['속도'].min()

In [11]:
max_0

93.0

In [12]:
max_1 = c1_data['속도'].max()
min_1 = c1_data['속도'].min()

In [119]:
c1_data = c1_data.reset_index()
c1_data

      index     속도  지점번호   교통량  요일  방향    거리  차선수  기능유형구분  합류도로수  제한속도  주말 유무
0       120  93.33  C-17   451   2   1  1138    3       1      2    80      0
1       121  91.75  C-17   369   2   1  1138    3       1      2    80      0
2       122  90.50  C-17   409   2   1  1138    3       1      2    80      0
3       123  91.08  C-17   750   2   1  1138    3       1      2    80      0
4       124  90.83  C-17  2544   2   1  1138    3       1      2    80      0
...     ...    ...   ...   ...  ..  ..   ...  ...     ...    ...   ...    ...
7507  73771  31.92  C-17  2692   1   1  1138    3       1      2    80      0
7508  73772  69.67  C-17  2669   1   1  1138    3       1      2    80      0
7509  73773  73.75  C-17  2295   1   1  1138    3       1      2    80      0
7510  73774  78.17  C-17  1409   1   1  1138    3       1      2    80      0
7511  73775  83.67  C-17   903   1   1  1138    3       1      2    80      0

[7512 rows x 12 columns]

In [120]:
c0_data = c0_data.reset_index()
c0_data

      index     속도  지점번호   교통량  요일  방향    거리  차선수  기능유형구분  합류도로수  제한속도  주말 유무
0        96  89.00  C-17   520   2   0  1575    3       1      3    80      0
1        97  87.50  C-17   415   2   0  1575    3       1      3    80      0
2        98  89.67  C-17   373   2   0  1575    3       1      3    80      0
3        99  87.67  C-17   559   2   0  1575    3       1      3    80      0
4       100  88.58  C-17  1324   2   0  1575    3       1      3    80      0
...     ...    ...   ...   ...  ..  ..   ...  ...     ...    ...   ...    ...
7507  73747  28.17  C-17  3184   1   0  1575    3       1      3    80      0
7508  73748  68.17  C-17  2877   1   0  1575    3       1      3    80      0
7509  73749  73.25  C-17  2432   1   0  1575    3       1      3    80      0
7510  73750  77.17  C-17  1667   1   0  1575    3       1      3    80      0
7511  73751  82.42  C-17   994   1   0  1575    3       1      3    80      0

[7512 rows x 12 columns]

In [121]:
c0_4lane = pd.DataFrame.copy(c0_data)
c0_4lane['차선수'] = 4
c0_2lane = pd.DataFrame.copy(c0_data)
c0_2lane['차선수'] = 2

In [17]:
c0_2lane

      index     속도  지점번호   교통량  요일  방향    거리  차선수  기능유형구분  합류도로수  제한속도  주말 유무
0        96  89.00  C-17   520   2   0  1575    2       1      3    80      0
1        97  87.50  C-17   415   2   0  1575    2       1      3    80      0
2        98  89.67  C-17   373   2   0  1575    2       1      3    80      0
3        99  87.67  C-17   559   2   0  1575    2       1      3    80      0
4       100  88.58  C-17  1324   2   0  1575    2       1      3    80      0
...     ...    ...   ...   ...  ..  ..   ...  ...     ...    ...   ...    ...
7507  73747  28.17  C-17  3184   1   0  1575    2       1      3    80      0
7508  73748  68.17  C-17  2877   1   0  1575    2       1      3    80      0
7509  73749  73.25  C-17  2432   1   0  1575    2       1      3    80      0
7510  73750  77.17  C-17  1667   1   0  1575    2       1      3    80      0
7511  73751  82.42  C-17   994   1   0  1575    2       1      3    80      0

[7512 rows x 12 columns]

In [18]:
c1_4lane = pd.DataFrame.copy(c1_data)
c1_4lane['차선수'] = 4
c1_2lane = pd.DataFrame.copy(c1_data)
c1_2lane['차선수'] = 2

In [ ]:
#c-17 상행 차선4개 c0_lane4, 차선 2개 c0_lane2
# 하행 차선 4개 c1_lane4, 차선 2개 c0_lane2

In [19]:


scaler = MinMaxScaler()
scale_cols = ['속도','교통량',  '거리', '제한속도']
       #'요일', '방향','차선수', '주말 유무'
       #'기능유형구분', '합류도로수', 
c0_4lane_scaled = scaler.fit_transform(c0_4lane[scale_cols])
c0_4lane_scaled = pd.DataFrame(c0_4lane_scaled)
c0_4lane_scaled.columns = scale_cols

In [20]:
c0_4lane_scaled

            속도       교통량   거리  제한속도
0     0.952897  0.081266  0.0   0.0
1     0.935233  0.056461  0.0   0.0
2     0.960787  0.046539  0.0   0.0
3     0.937235  0.090480  0.0   0.0
4     0.947951  0.271202  0.0   0.0
...        ...       ...  ...   ...
7507  0.236576  0.710607  0.0   0.0
7508  0.707607  0.638082  0.0   0.0
7509  0.767428  0.532955  0.0   0.0
7510  0.813589  0.352232  0.0   0.0
7511  0.875412  0.193244  0.0   0.0

[7512 rows x 4 columns]

In [21]:
c0_4lane_scaled['요일'] = c0_4lane['요일']
c0_4lane_scaled['방향'] = c0_4lane['방향']
c0_4lane_scaled['차선수'] = c0_4lane['차선수']
c0_4lane_scaled['주말 유무'] = c0_4lane['주말 유무']
c0_4lane_scaled['기능유형구분'] = c0_4lane['기능유형구분']
c0_4lane_scaled['합류도로수'] = c0_4lane['합류도로수']

In [22]:
c0_4lane_scaled

            속도       교통량   거리  제한속도  요일  방향  차선수  주말 유무  기능유형구분  합류도로수
0     0.952897  0.081266  0.0   0.0   2   0    4      0       1      3
1     0.935233  0.056461  0.0   0.0   2   0    4      0       1      3
2     0.960787  0.046539  0.0   0.0   2   0    4      0       1      3
3     0.937235  0.090480  0.0   0.0   2   0    4      0       1      3
4     0.947951  0.271202  0.0   0.0   2   0    4      0       1      3
...        ...       ...  ...   ...  ..  ..  ...    ...     ...    ...
7507  0.236576  0.710607  0.0   0.0   1   0    4      0       1      3
7508  0.707607  0.638082  0.0   0.0   1   0    4      0       1      3
7509  0.767428  0.532955  0.0   0.0   1   0    4      0       1      3
7510  0.813589  0.352232  0.0   0.0   1   0    4      0       1      3
7511  0.875412  0.193244  0.0   0.0   1   0    4      0       1      3

[7512 rows x 10 columns]

In [23]:

c0_2lane_scaled = scaler.fit_transform(c0_2lane[scale_cols])
c0_2lane_scaled = pd.DataFrame(c0_2lane_scaled)
c0_2lane_scaled.columns = scale_cols

c0_2lane_scaled['요일'] = c0_2lane['요일']
c0_2lane_scaled['방향'] = c0_2lane['방향']
c0_2lane_scaled['차선수'] = c0_2lane['차선수']
c0_2lane_scaled['주말 유무'] = c0_2lane['주말 유무']
c0_2lane_scaled['기능유형구분'] = c0_2lane['기능유형구분']
c0_2lane_scaled['합류도로수'] = c0_2lane['합류도로수']

In [24]:
c1_4lane_scaled = scaler.fit_transform(c1_4lane[scale_cols])
c1_4lane_scaled = pd.DataFrame(c1_4lane_scaled)
c1_4lane_scaled.columns = scale_cols

c1_4lane_scaled['요일'] = c1_4lane['요일']
c1_4lane_scaled['방향'] = c1_4lane['방향']
c1_4lane_scaled['차선수'] = c1_4lane['차선수']
c1_4lane_scaled['주말 유무'] = c1_4lane['주말 유무']
c1_4lane_scaled['기능유형구분'] = c1_4lane['기능유형구분']
c1_4lane_scaled['합류도로수'] = c1_4lane['합류도로수']

In [25]:
c1_2lane_scaled = scaler.fit_transform(c1_2lane[scale_cols])
c1_2lane_scaled = pd.DataFrame(c1_2lane_scaled)
c1_2lane_scaled.columns = scale_cols

c1_2lane_scaled['요일'] = c1_2lane['요일']
c1_2lane_scaled['방향'] = c1_2lane['방향']
c1_2lane_scaled['차선수'] = c1_2lane['차선수']
c1_2lane_scaled['주말 유무'] = c1_2lane['주말 유무']
c1_2lane_scaled['기능유형구분'] = c1_2lane['기능유형구분']
c1_2lane_scaled['합류도로수'] = c1_2lane['합류도로수']

In [27]:
c1_4lane_scaled

            속도       교통량   거리  제한속도  요일  방향  차선수  주말 유무  기능유형구분  합류도로수
0     0.952522  0.063653  0.0   0.0   2   1    4      0       1      2
1     0.933769  0.046651  0.0   0.0   2   1    4      0       1      2
2     0.918932  0.054945  0.0   0.0   2   1    4      0       1      2
3     0.925816  0.125648  0.0   0.0   2   1    4      0       1      2
4     0.922849  0.497616  0.0   0.0   2   1    4      0       1      2
...        ...       ...  ...   ...  ..  ..  ...    ...     ...    ...
7507  0.223620  0.528302  0.0   0.0   1   1    4      0       1      2
7508  0.671691  0.523533  0.0   0.0   1   1    4      0       1      2
7509  0.720119  0.445988  0.0   0.0   1   1    4      0       1      2
7510  0.772582  0.262285  0.0   0.0   1   1    4      0       1      2
7511  0.837864  0.157371  0.0   0.0   1   1    4      0       1      2

[7512 rows x 10 columns]

In [131]:
c0_4lane_scaled.loc[24]

속도        0.958785
교통량       0.094259
거리        0.000000
제한속도      0.000000
요일        3.000000
방향        0.000000
차선수       4.000000
주말 유무     0.000000
기능유형구분    1.000000
합류도로수     3.000000
Name: 24, dtype: float64

In [28]:
c0_2lane_scaled

            속도       교통량   거리  제한속도  요일  방향  차선수  주말 유무  기능유형구분  합류도로수
0     0.952897  0.081266  0.0   0.0   2   0    2      0       1      3
1     0.935233  0.056461  0.0   0.0   2   0    2      0       1      3
2     0.960787  0.046539  0.0   0.0   2   0    2      0       1      3
3     0.937235  0.090480  0.0   0.0   2   0    2      0       1      3
4     0.947951  0.271202  0.0   0.0   2   0    2      0       1      3
...        ...       ...  ...   ...  ..  ..  ...    ...     ...    ...
7507  0.236576  0.710607  0.0   0.0   1   0    2      0       1      3
7508  0.707607  0.638082  0.0   0.0   1   0    2      0       1      3
7509  0.767428  0.532955  0.0   0.0   1   0    2      0       1      3
7510  0.813589  0.352232  0.0   0.0   1   0    2      0       1      3
7511  0.875412  0.193244  0.0   0.0   1   0    2      0       1      3

[7512 rows x 10 columns]

In [29]:
c1_4lane_scaled

            속도       교통량   거리  제한속도  요일  방향  차선수  주말 유무  기능유형구분  합류도로수
0     0.952522  0.063653  0.0   0.0   2   1    4      0       1      2
1     0.933769  0.046651  0.0   0.0   2   1    4      0       1      2
2     0.918932  0.054945  0.0   0.0   2   1    4      0       1      2
3     0.925816  0.125648  0.0   0.0   2   1    4      0       1      2
4     0.922849  0.497616  0.0   0.0   2   1    4      0       1      2
...        ...       ...  ...   ...  ..  ..  ...    ...     ...    ...
7507  0.223620  0.528302  0.0   0.0   1   1    4      0       1      2
7508  0.671691  0.523533  0.0   0.0   1   1    4      0       1      2
7509  0.720119  0.445988  0.0   0.0   1   1    4      0       1      2
7510  0.772582  0.262285  0.0   0.0   1   1    4      0       1      2
7511  0.837864  0.157371  0.0   0.0   1   1    4      0       1      2

[7512 rows x 10 columns]

In [30]:
c1_2lane_scaled

            속도       교통량   거리  제한속도  요일  방향  차선수  주말 유무  기능유형구분  합류도로수
0     0.952522  0.063653  0.0   0.0   2   1    2      0       1      2
1     0.933769  0.046651  0.0   0.0   2   1    2      0       1      2
2     0.918932  0.054945  0.0   0.0   2   1    2      0       1      2
3     0.925816  0.125648  0.0   0.0   2   1    2      0       1      2
4     0.922849  0.497616  0.0   0.0   2   1    2      0       1      2
...        ...       ...  ...   ...  ..  ..  ...    ...     ...    ...
7507  0.223620  0.528302  0.0   0.0   1   1    2      0       1      2
7508  0.671691  0.523533  0.0   0.0   1   1    2      0       1      2
7509  0.720119  0.445988  0.0   0.0   1   1    2      0       1      2
7510  0.772582  0.262285  0.0   0.0   1   1    2      0       1      2
7511  0.837864  0.157371  0.0   0.0   1   1    2      0       1      2

[7512 rows x 10 columns]

In [31]:
feature_cols = ['교통량', '요일', '방향', '거리', '차선수',
       '기능유형구분', '합류도로수', '제한속도', '주말 유무']
label_cols = ['속도']

In [32]:
test04_feature = c0_4lane_scaled[feature_cols]
test02_feature = c0_2lane_scaled[feature_cols]
test14_feature = c1_4lane_scaled[feature_cols]
test12_feature = c1_2lane_scaled[feature_cols]
test04_label = c0_4lane_scaled[label_cols]
test02_label = c0_2lane_scaled[label_cols]
test14_label = c1_4lane_scaled[label_cols]
test12_label = c1_2lane_scaled[label_cols]
test04_feature.shape, test04_label.shape

((7512, 9), (7512, 1))

In [33]:
test04_feature, test04_label = make_dataset(test04_feature, test04_label, 24)
test02_feature, test02_label = make_dataset(test02_feature, test02_label, 24)
test14_feature, test14_label = make_dataset(test14_feature, test14_label, 24)
test12_feature, test12_label = make_dataset(test12_feature, test12_label, 24)
test04_feature.shape, test04_label.shape

((7488, 24, 9), (7488, 1))

In [126]:
test04_label

array([[0.95878474],
       [0.97056053],
       [0.92145549],
       ...,
       [0.76742817],
       [0.81358926],
       [0.87541215]])

In [34]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

model = Sequential()
model.add(LSTM(16, 
               input_shape=((24, 9)), 
               activation='relu', 
               return_sequences=False)
          )

model.add(Dense(1))

In [35]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [36]:
model.load_weights(filename)

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 16)                1664

 dense (Dense)               (None, 1)                 17

=================================================================
Total params: 1,681
Trainable params: 1,681
Non-trainable params: 0
_________________________________________________________________

In [103]:
pred04 = model.predict(test04_feature) #상행 4차선 변경
pred02 = model.predict(test02_feature) #상행 2차선 변경
pred14 = model.predict(test14_feature) #하행 4차선 변경
pred12 = model.predict(test12_feature) #하행 2차선 변경

234/234 [==============================] - 1s 4ms/step
234/234 [==============================] - 1s 4ms/step
234/234 [==============================] - 1s 4ms/step
234/234 [==============================] - 1s 3ms/step

In [104]:
pred12

array([[0.8583659 ],
       [1.0933057 ],
       [0.9523039 ],
       ...,
       [0.7603365 ],
       [0.7885281 ],
       [0.82916844]], dtype=float32)

In [105]:
min_1*2/3

8.72

In [106]:
pred04 = pred04*((max_0-min_0)) + (min_0)
pred02 = pred02*((max_0-min_0))
pred14 = pred14*(max_1-min_1) + min_1
pred12 = pred12*((max_1-min_1))

In [107]:
pred04 = pd.DataFrame(pred04)
pred02 = pd.DataFrame(pred02)
pred14 = pd.DataFrame(pred14)
pred12 = pd.DataFrame(pred12)

In [108]:
pred04.columns = ['4차선 속도']

In [109]:
pred04

          4차선 속도
0     113.048630
1     106.663803
2     109.018723
3     108.794128
4     108.028191
...          ...
7483   86.756050
7484   96.627808
7485  101.716507
7486  105.268692
7487  113.965034

[7488 rows x 1 columns]

In [110]:
pred02.columns = ['2차선 속도']
pred14.columns = ['4차선 속도']
pred12.columns = ['2차선 속도']

In [111]:
pred02

         2차선 속도
0     51.961266
1     58.181419
2     61.035759
3     64.805885
4     64.363083
...         ...
7483  25.812105
7484  31.305967
7485  34.493092
7486  36.624271
7487  47.180836

[7488 rows x 1 columns]

In [ ]:
#24시간이 312개인 데이터 -> 각시간별 평균

          4차선 속도
0     262.607605
1     258.925293
2     268.728027
3     269.250732
4     269.227905
...          ...
7483   59.042812
7484   61.142548
7485   62.347843
7486   64.390762
7487   68.316147

[7488 rows x 1 columns]

In [142]:
c0_data = c0_data.drop(['index'], axis=1)

In [143]:
c1_data = c1_data.drop(['index'], axis=1)

In [133]:
c0_data = c0_data.drop(c0_data.index[0], axis=0)
c0_data

      index     속도  지점번호   교통량  요일  방향    거리  차선수  기능유형구분  합류도로수  제한속도  주말 유무
24      336  89.50  C-17   575   3   0  1575    3       1      3    80      0
25      337  90.50  C-17   498   3   0  1575    3       1      3    80      0
26      338  86.33  C-17   492   3   0  1575    3       1      3    80      0
27      339  85.42  C-17   608   3   0  1575    3       1      3    80      0
28      340  86.92  C-17  1287   3   0  1575    3       1      3    80      0
...     ...    ...   ...   ...  ..  ..   ...  ...     ...    ...   ...    ...
7507  73747  28.17  C-17  3184   1   0  1575    3       1      3    80      0
7508  73748  68.17  C-17  2877   1   0  1575    3       1      3    80      0
7509  73749  73.25  C-17  2432   1   0  1575    3       1      3    80      0
7510  73750  77.17  C-17  1667   1   0  1575    3       1      3    80      0
7511  73751  82.42  C-17   994   1   0  1575    3       1      3    80      0

[7488 rows x 12 columns]

In [136]:
c1_data = c1_data.drop(c1_data.index[0], axis=0)

In [137]:
c1_data

      index     속도  지점번호   교통량  요일  방향    거리  차선수  기능유형구분  합류도로수  제한속도  주말 유무
24      360  89.92  C-17   577   3   1  1138    3       1      2    80      0
25      361  88.67  C-17   455   3   1  1138    3       1      2    80      0
26      362  88.58  C-17   484   3   1  1138    3       1      2    80      0
27      363  84.50  C-17   726   3   1  1138    3       1      2    80      0
28      364  87.25  C-17  2193   3   1  1138    3       1      2    80      0
...     ...    ...   ...   ...  ..  ..   ...  ...     ...    ...   ...    ...
7507  73771  31.92  C-17  2692   1   1  1138    3       1      2    80      0
7508  73772  69.67  C-17  2669   1   1  1138    3       1      2    80      0
7509  73773  73.75  C-17  2295   1   1  1138    3       1      2    80      0
7510  73774  78.17  C-17  1409   1   1  1138    3       1      2    80      0
7511  73775  83.67  C-17   903   1   1  1138    3       1      2    80      0

[7488 rows x 12 columns]

In [138]:
c0_data = c0_data.reset_index(drop = True)
c1_data = c1_data.reset_index(drop = True)

In [139]:
c0_data['4차선 속도'] = pred04['4차선 속도']
c0_data['2차선 속도'] = pred02['2차선 속도']
c1_data['4차선 속도'] = pred14['4차선 속도']
c1_data['2차선 속도'] = pred12['2차선 속도']

In [144]:
c0_data

,속도,지점번호,교통량,요일,방향,거리,차선수,기능유형구분,합류도로수,제한속도,주말 유무,4차선 속도,2차선 속도
0,89.50,C-17,575,3,0,1575,3,1,3,80,0,113.048630,51.961266
1,90.50,C-17,498,3,0,1575,3,1,3,80,0,106.663803,58.181419
2,86.33,C-17,492,3,0,1575,3,1,3,80,0,109.018723,61.035759
3,85.42,C-17,608,3,0,1575,3,1,3,80,0,108.794128,64.805885
4,86.92,C-17,1287,3,0,1575,3,1,3,80,0,108.028191,64.363083
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7483,28.17,C-17,3184,1,0,1575,3,1,3,80,0,86.756050,25.812105
7484,68.17,C-17,2877,1,0,1575,3,1,3,80,0,96.627808,31.305967
7485,73.25,C-17,2432,1,0,1575,3,1,3,80,0,101.716507,34.493092
7486,77.17,C-17,1667,1,0,1575,3,1,3,80,0,105.268692,36.624271
7487,82.42,C-17,994,1,0,1575,3,1,3,80,0,113.965034,47.180836

In [145]:
c1_data

,속도,지점번호,교통량,요일,방향,거리,차선수,기능유형구분,합류도로수,제한속도,주말 유무,4차선 속도,2차선 속도
0,89.92,C-17,577,3,1,1138,3,1,2,80,0,100.531342,72.317329
1,88.67,C-17,455,3,1,1138,3,1,2,80,0,110.478745,92.111008
2,88.58,C-17,484,3,1,1138,3,1,2,80,0,102.181236,80.231606
3,84.50,C-17,726,3,1,1138,3,1,2,80,0,103.499252,94.932472
4,87.25,C-17,2193,3,1,1138,3,1,2,80,0,104.113029,97.757408
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7483,31.92,C-17,2692,1,1,1138,3,1,2,80,0,99.725395,62.627258
7484,69.67,C-17,2669,1,1,1138,3,1,2,80,0,98.502594,63.132702
7485,73.75,C-17,2295,1,1,1138,3,1,2,80,0,99.251930,64.058350
7486,78.17,C-17,1409,1,1,1138,3,1,2,80,0,100.491585,66.433495
7487,83.67,C-17,903,1,1,1138,3,1,2,80,0,102.976776,69.857445

In [146]:
c0_data.to_csv('/content/drive/MyDrive/공모전/분석/상행변화1.csv')
c1_data.to_csv('/content/drive/MyDrive/공모전/분석/하행변화1.csv')

In [147]:
7488/24

312.0

In [149]:
velo_c0 = c0_data[['속도', '4차선 속도', '2차선 속도']]
velo_c1 = c1_data[['속도', '4차선 속도', '2차선 속도']]

In [154]:
velo_c0

         속도      4차선 속도     2차선 속도
0     89.50  113.048630  51.961266
1     90.50  106.663803  58.181419
2     86.33  109.018723  61.035759
3     85.42  108.794128  64.805885
4     86.92  108.028191  64.363083
...     ...         ...        ...
7483  28.17   86.756050  25.812105
7484  68.17   96.627808  31.305967
7485  73.25  101.716507  34.493092
7486  77.17  105.268692  36.624271
7487  82.42  113.965034  47.180836

[7488 rows x 3 columns]

In [ ]:
#0 -> 01시 23-> 24시
# 새벽시간은 제외, (05시~ 22시) 만 판단

In [167]:
list_05 = []
for i in range(0,312) :
  j= i*24+4
  list_05.append(velo_c0.loc[j])

a5 = sum(list_05)
a5 = a5/312
a5

속도         85.326250
4차선 속도    110.999857
2차선 속도     71.963747
dtype: float64

In [169]:
a5 = pd.DataFrame(a5).transpose()
a5

         속도      4차선 속도     2차선 속도
0  85.32625  110.999857  71.963747

In [171]:
list_06 = []
for i in range(0,312) :
  j= i*24+5
  list_06.append(velo_c0.loc[j])

a6 = sum(list_06)
a6 = a6/312

list_07 = []

for i in range(0,312) :
  j= i*24+6
  list_07.append(velo_c0.loc[j])

a7 = sum(list_07)
a7 = a7/312

list_08 = []

for i in range(0,312) :
  j= i*24+7
  list_08.append(velo_c0.loc[j])

a8 = sum(list_08)/312

list_09 = []
for i in range(0,312) :
  j= i*24+8
  list_09.append(velo_c0.loc[j])

a9 = sum(list_09)
a9 = a9/312

list_10 = []
for i in range(0,312) :
  j= i*24+9
  list_10.append(velo_c0.loc[j])

a10 = sum(list_10)
a10 = a10/312

list_11 = []
for i in range(0,312) :
  j= i*24+10
  list_11.append(velo_c0.loc[j])

a11 = sum(list_11)
a11 = a11/312

list_12 = []
for i in range(0,312) :
  j= i*24+11
  list_12.append(velo_c0.loc[j])

a12 = sum(list_12)
a12 = a12/312

list_13 = []
for i in range(0,312) :
  j= i*24+12
  list_13.append(velo_c0.loc[j])

a13 = sum(list_13)
a13 = a13/312

list_14 = []
for i in range(0,312) :
  j= i*24+13
  list_14.append(velo_c0.loc[j])

a14 = sum(list_14)
a14 = a14/312

list_15 = []
for i in range(0,312) :
  j= i*24+14
  list_15.append(velo_c0.loc[j])

a15 = sum(list_15)
a15 = a15/312

list_16 = []
for i in range(0,312) :
  j= i*24+15
  list_16.append(velo_c0.loc[j])

a16 = sum(list_16)
a16 = a16/312

list_17 = []
for i in range(0,312) :
  j= i*24+16
  list_17.append(velo_c0.loc[j])

a17 = sum(list_17)
a17 = a17/312

list_18 = []
for i in range(0,312) :
  j= i*24+17
  list_18.append(velo_c0.loc[j])

a18 = sum(list_18)
a18 = a18/312


list_19 = []
for i in range(0,312) :
  j= i*24+18
  list_19.append(velo_c0.loc[j])

a19 = sum(list_19)
a19 = a19/312


list_20 = []
for i in range(0,312) :
  j= i*24+19
  list_20.append(velo_c0.loc[j])

a20 = sum(list_20)
a20 = a20/312


list_21 = []
for i in range(0,312) :
  j= i*24+20
  list_21.append(velo_c0.loc[j])

a21 = sum(list_21)
a21 = a21/312


list_22 = []
for i in range(0,312) :
  j= i*24+21
  list_22.append(velo_c0.loc[j])

a22 = sum(list_22)
a22 = a22/312

In [172]:
a6 = pd.DataFrame(a6).transpose()
a7 = pd.DataFrame(a7).transpose()
a8 = pd.DataFrame(a8).transpose()
a9 = pd.DataFrame(a9).transpose()
a10 = pd.DataFrame(a10).transpose()
a11 = pd.DataFrame(a11).transpose()
a12 = pd.DataFrame(a12).transpose()
a13 = pd.DataFrame(a13).transpose()
a14 = pd.DataFrame(a14).transpose()
a15 = pd.DataFrame(a15).transpose()
a16 = pd.DataFrame(a16).transpose()
a17 = pd.DataFrame(a17).transpose()
a18 = pd.DataFrame(a18).transpose()
a19 = pd.DataFrame(a19).transpose()
a20 = pd.DataFrame(a20).transpose()
a21 = pd.DataFrame(a21).transpose()
a22 = pd.DataFrame(a22).transpose()

total = pd.concat([a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22])

In [173]:
total

          속도      4차선 속도     2차선 속도
0  85.326250  110.999857  71.963747
0  77.633942  106.594845  63.123982
0  44.981923   88.522452  50.029299
0  35.494327   93.316212  38.994483
0  34.144519   90.435929  41.534546
0  34.887596   93.375566  40.742532
0  30.502853   88.578129  39.915103
0  27.444615   89.889816  29.107401
0  29.224776   90.099928  41.772869
0  32.962179   90.534087  31.432199
0  27.153814   88.922758  25.179557
0  21.545096   87.434487  17.535708
0  19.012788   84.689215  11.227944
0  18.477372   88.232227  18.903255
0  23.208205   90.813925  17.541626
0  37.692083   90.676244  28.015262
0  57.328558   89.938268  51.310296
0  64.133782   94.043176  40.883807

In [174]:
list_05 = []
for i in range(0,312) :
  j= i*24+4
  list_05.append(velo_c1.loc[j])

a5 = sum(list_05)
a5 = a5/312

list_06 = []
for i in range(0,312) :
  j= i*24+5
  list_06.append(velo_c1.loc[j])

a6 = sum(list_06)
a6 = a6/312

list_07 = []

for i in range(0,312) :
  j= i*24+6
  list_07.append(velo_c1.loc[j])

a7 = sum(list_07)
a7 = a7/312

list_08 = []

for i in range(0,312) :
  j= i*24+7
  list_08.append(velo_c1.loc[j])

a8 = sum(list_08)/312

list_09 = []
for i in range(0,312) :
  j= i*24+8
  list_09.append(velo_c1.loc[j])

a9 = sum(list_09)
a9 = a9/312

list_10 = []
for i in range(0,312) :
  j= i*24+9
  list_10.append(velo_c1.loc[j])

a10 = sum(list_10)
a10 = a10/312

list_11 = []
for i in range(0,312) :
  j= i*24+10
  list_11.append(velo_c1.loc[j])

a11 = sum(list_11)
a11 = a11/312

list_12 = []
for i in range(0,312) :
  j= i*24+11
  list_12.append(velo_c1.loc[j])

a12 = sum(list_12)
a12 = a12/312

list_13 = []
for i in range(0,312) :
  j= i*24+12
  list_13.append(velo_c1.loc[j])

a13 = sum(list_13)
a13 = a13/312

list_14 = []
for i in range(0,312) :
  j= i*24+13
  list_14.append(velo_c1.loc[j])

a14 = sum(list_14)
a14 = a14/312

list_15 = []
for i in range(0,312) :
  j= i*24+14
  list_15.append(velo_c1.loc[j])

a15 = sum(list_15)
a15 = a15/312

list_16 = []
for i in range(0,312) :
  j= i*24+15
  list_16.append(velo_c1.loc[j])

a16 = sum(list_16)
a16 = a16/312

list_17 = []
for i in range(0,312) :
  j= i*24+16
  list_17.append(velo_c1.loc[j])

a17 = sum(list_17)
a17 = a17/312

list_18 = []
for i in range(0,312) :
  j= i*24+17
  list_18.append(velo_c1.loc[j])

a18 = sum(list_18)
a18 = a18/312


list_19 = []
for i in range(0,312) :
  j= i*24+18
  list_19.append(velo_c1.loc[j])

a19 = sum(list_19)
a19 = a19/312


list_20 = []
for i in range(0,312) :
  j= i*24+19
  list_20.append(velo_c1.loc[j])

a20 = sum(list_20)
a20 = a20/312


list_21 = []
for i in range(0,312) :
  j= i*24+20
  list_21.append(velo_c1.loc[j])

a21 = sum(list_21)
a21 = a21/312


list_22 = []
for i in range(0,312) :
  j= i*24+21
  list_22.append(velo_c1.loc[j])

a22 = sum(list_22)
a22 = a22/312

In [175]:
a5 = pd.DataFrame(a5).transpose()
a6 = pd.DataFrame(a6).transpose()
a7 = pd.DataFrame(a7).transpose()
a8 = pd.DataFrame(a8).transpose()
a9 = pd.DataFrame(a9).transpose()
a10 = pd.DataFrame(a10).transpose()
a11 = pd.DataFrame(a11).transpose()
a12 = pd.DataFrame(a12).transpose()
a13 = pd.DataFrame(a13).transpose()
a14 = pd.DataFrame(a14).transpose()
a15 = pd.DataFrame(a15).transpose()
a16 = pd.DataFrame(a16).transpose()
a17 = pd.DataFrame(a17).transpose()
a18 = pd.DataFrame(a18).transpose()
a19 = pd.DataFrame(a19).transpose()
a20 = pd.DataFrame(a20).transpose()
a21 = pd.DataFrame(a21).transpose()
a22 = pd.DataFrame(a22).transpose()

total_1 = pd.concat([a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22])
total_1

          속도      4차선 속도      2차선 속도
0  86.029551   93.035508   81.006589
0  84.707500  123.255164  107.826159
0  77.771186  115.231677  104.968820
0  73.757340   96.145118   80.702370
0  72.909327  108.042414  100.811551
0  71.458622  115.969942  100.289481
0  67.067212   97.458146  123.398060
0  66.443942  116.245169  131.579613
0  68.173558  101.643181   35.105943
0  68.026058  111.165499  115.590258
0  66.197949  105.120119  105.621029
0  64.199423  107.138096   65.092925
0  61.311474  106.216056   82.085188
0  48.509006  107.601688  124.788600
0  41.244712  108.167991   68.350516
0  46.010609  111.159349   90.620887
0  64.470096  110.200386  118.767770
0  70.823814  112.391703   62.422344

In [176]:
total.to_csv('/content/drive/MyDrive/공모전/분석/상행시간별평균.csv')
total_1.to_csv('/content/drive/MyDrive/공모전/분석/하행시간별평균.csv')