In [4]:
!pip install geopandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib
import geopandas as gpd
import matplotlib.pyplot as plt

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geopandas
  Downloading geopandas-0.12.2-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 21.8 MB/s eta 0:00:00
Collecting fiona>=1.8
  Downloading Fiona-1.9.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.1/16.1 MB 57.3 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from geopandas) (1.4.4)
Requirement already satisfied: shapely>=1.7 in /usr/local/lib/python3.9/dist-packages (from geopandas) (2.0.1)
Collecting pyproj>=2.6.1.post1
  Downloading pyproj-3.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 95.4 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from geopandas) (23.0)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (8.1.3)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (6.1.0)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (2022.12.7)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.9/dist-packages (from fiona>=1.8->geopandas) (22.2.0)
Collecting munch>=2.3.2
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.0->geopandas) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1.0.0->geopandas) (2022.7.1)
Requirement already satisfied: six in /usr/local/lib/python3.9/dist-packages (from munch>=2.3.2->fiona>=1.8->geopandas) (1.16.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata->fiona>=1.8->geopandas) (3.15.0)
Installing collected packages: pyproj, munch, cligj, click-plugins, fiona, geopandas
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.3 geopandas-0.12.2 munch-2.5.0 pyproj-3.5.0

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
cd /content/drive/MyDrive

/content/drive/MyDrive

In [13]:
plt.rcParams["font.family"] = 'NanumGothic'
plt.rcParams["figure.figsize"] = (10, 10)

seoul = gpd.read_file('sig.shp', encoding = 'euc-kr')
seoul

,SIG_CD,SIG_ENG_NM,SIG_KOR_NM,geometry
0,11110,Jongno-gu,종로구,"POLYGON ((956615.453 1953567.199, 956621.579 1..."
1,11140,Jung-gu,중구,"POLYGON ((957890.386 1952616.746, 957909.908 1..."
2,11170,Yongsan-gu,용산구,"POLYGON ((953115.761 1950834.084, 953114.206 1..."
3,11200,Seongdong-gu,성동구,"POLYGON ((959681.109 1952649.605, 959842.412 1..."
4,11215,Gwangjin-gu,광진구,"POLYGON ((964825.058 1952633.250, 964875.565 1..."
...,...,...,...,...
245,48870,Hamyang-gun,함양군,"POLYGON ((1017715.723 1751280.191, 1017761.619..."
246,48880,Geochang-gun,거창군,"POLYGON ((1034571.593 1767759.812, 1034559.208..."
247,48890,Hapcheon-gun,합천군,"POLYGON ((1054066.576 1759517.415, 1054101.450..."
248,50110,Jeju-si,제주시,"MULTIPOLYGON (((874410.953 1480515.382, 874408..."
249,50130,Seogwipo-si,서귀포시,"MULTIPOLYGON (((885004.560 1458756.461, 884996..."

In [23]:
df = gpd.read_file('MOCT_LINK.shp', encoding = 'euc-kr')
df

,LINK_ID,F_NODE,T_NODE,LANES,ROAD_RANK,ROAD_TYPE,ROAD_NO,ROAD_NAME,ROAD_USE,MULTI_LINK,CONNECT,MAX_SPD,REST_VEH,REST_W,REST_H,LENGTH,REMARK,geometry
0,3521214301,3520490601,3520490701,1,107,000,-,강변로,0,0,000,40,0,0.0,0,278.145912,NaN,"LINESTRING (399466.133 365641.146, 399434.536 ..."
1,3521214201,3520490701,3520490501,1,107,000,-,강변로,0,0,000,40,0,0.0,0,224.421362,NaN,"LINESTRING (399312.204 365409.499, 399283.198 ..."
2,1540081300,1540027000,1540028000,3,104,004,-,호국로,0,0,000,70,0,0.0,0,766.202760,NaN,"LINESTRING (343767.841 372061.103, 343660.725 ..."
3,1540081400,1540028000,1540027000,3,104,004,-,호국로,1,0,000,70,0,0.0,0,775.749947,NaN,"LINESTRING (343486.286 372773.927, 343556.668 ..."
4,1540084700,1540028000,1540028300,3,104,000,-,호국로,0,0,000,70,0,0.0,0,156.431121,NaN,"LINESTRING (343524.234 372788.254, 343494.072 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538614,3970321601,3970090801,3970090701,1,103,003,3,-,0,0,000,60,0,0.0,0,156.907828,도로명없음,"LINESTRING (283164.227 353701.052, 283187.796 ..."
538615,3970321701,3970090701,3970090801,1,103,003,3,-,0,0,000,60,0,0.0,0,165.346625,도로명없음,"LINESTRING (283256.322 353570.319, 283246.198 ..."
538616,3970321201,3970090701,3970090601,1,103,000,3,-,0,0,000,60,0,0.0,0,226.106041,도로명없음,"LINESTRING (283242.861 353566.519, 283262.178 ..."
538617,3970321301,3970090601,3970090701,1,103,000,3,-,0,0,000,60,0,0.0,0,232.573758,도로명없음,"LINESTRING (283275.357 353341.053, 283277.943 ..."
538618,3970321401,3970012600,3970090601,1,103,000,3,웅양로,0,0,000,60,0,0.0,0,2587.841620,NaN,"LINESTRING (282626.203 355613.501, 282624.117 ..."

In [25]:
df2 = gpd.read_file('MOCT_NODE.shp', encoding = 'euc-kr')
df2

WARNING:fiona._env:One or several characters couldn't be converted correctly from EUC-KR to UTF-8.  This warning will not be emitted anymore

,NODE_ID,NODE_TYPE,NODE_NAME,TURN_P,REMARK,geometry
0,3520490701,101,-,0,NaN,POINT (399316.904 365407.646)
1,3300002000,101,태평삼거리,0,NaN,POINT (229039.507 283709.367)
2,3300003000,101,태안삼거리,0,NaN,POINT (231445.784 285032.095)
3,3300004300,101,압록사거리,1,NaN,POINT (234183.082 288713.159)
4,2180135401,101,송희농원,0,NaN,POINT (184609.478 560783.969)
...,...,...,...,...,...,...
200211,2450048401,101,-,0,교차로명없음,POINT (209268.312 525908.908)
200212,2310325101,101,-,0,교차로명없음,POINT (227143.066 497092.409)
200213,2310325001,101,-,0,교차로명없음,POINT (226735.516 496341.319)
200214,2290226101,104,산단TG,0,NaN,POINT (180632.817 580614.538)
200215,2290226001,104,산단TG,0,NaN,POINT (180606.161 580595.138)

In [24]:
mapping = pd.read_excel('서울특별시 표준링크 매핑정보.xlsx')
mapping = mapping.drop("표준링크순서", axis = 1)
mapping = mapping.drop_duplicates(subset=['서비스링크'])

mapping

speed = pd.merge(left=speed, right=mapping, how = 'inner', lefh_on = '링크아이디', right_on = '서비스링크')

NameError: ignored