In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

csv = '/content/drive/MyDrive/공모전/데이터/다시한거/합류도로, 제한속도, 밀도.xlsx'
csvv = pd.read_excel(csv)

In [4]:
csvv

,일자,요일,도로명,지점번호,시점명,종점명,방향,거리,차선수,기능유형구분,...,15시_밀도,16시_밀도,17시_밀도,18시_밀도,19시_밀도,20시_밀도,21시_밀도,22시_밀도,23시_밀도,24시_밀도
0,20220302,수,강동대로,C-19,올림픽대교북단,올림픽대교남단,상행,1228,3,주간선도로,...,40.191388,46.346905,50.138198,54.988705,37.399137,24.942922,20.322342,17.903373,8.917890,3.854506
1,20220302,수,강동대로,C-19,올림픽대교남단,올림픽대교북단,하행,1228,3,주간선도로,...,29.986272,31.889687,38.748739,38.933008,36.399420,22.071130,18.616304,13.291139,7.706662,3.074940
2,20220302,수,동일로,D-07,화양사거리,군자교동단,상행,1350,3,주간선도로,...,46.119134,46.709062,50.119822,46.543296,39.737991,36.775994,33.851784,26.639582,25.360502,11.751802
3,20220302,수,동일로,D-07,군자교동단,화양사거리,하행,1350,2,주간선도로,...,85.569387,95.285041,105.053996,113.472403,107.668440,80.351648,70.289256,66.056572,39.118774,20.021149
4,20220302,수,분당수서로,C-17,청담대교북단,청담대교남단,상행,1575,3,도시고속도로,...,100.255900,125.795276,178.714859,191.333333,111.238095,60.417582,34.933404,30.703790,15.631902,7.900971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3073,20230131,화,분당수서로,C-17,청담대교남단,청담대교북단,하행,1138,3,도시고속도로,...,45.382702,48.665741,36.911072,88.814130,151.407329,84.335840,38.309172,31.118644,18.024818,10.792399
3074,20230131,화,송파대로,C-18,잠실대교북단,잠실대교남단,상행,1171,4,주간선도로,...,45.729304,47.124662,52.676827,60.893967,49.381464,42.977970,39.223736,32.823036,25.052595,16.164431
3075,20230131,화,송파대로,C-18,잠실대교남단,잠실대교북단,하행,1175,4,주간선도로,...,50.814785,51.977401,57.039641,67.510721,64.708423,47.678462,42.008432,35.752638,26.995434,16.028418
3076,20230131,화,천호대로,C-20,천호대교북단,천호대교남단,상행,1001,3,주간선도로,...,37.824074,41.248499,44.727973,43.544121,36.685552,26.260504,22.192573,20.237590,14.147326,9.588247
3077,20230131,화,천호대로,C-20,천호대교남단,천호대교북단,하행,1001,3,주간선도로,...,45.221920,45.415343,55.273152,83.181404,66.394895,39.885401,31.845436,25.041356,19.175554,11.314635

In [5]:
csvv.columns

Index(['일자', '요일', '도로명', '지점번호', '시점명', '종점명', '방향', '거리', '차선수', '기능유형구분',
       '도심/외곽구분', '권역구분', '01시_속도', '02시_속도', '03시_속도', '04시_속도', '05시_속도',
       '06시_속도', '07시_속도', '08시_속도', '09시_속도', '10시_속도', '11시_속도', '12시_속도',
       '13시_속도', '14시_속도', '15시_속도', '16시_속도', '17시_속도', '18시_속도', '19시_속도',
       '20시_속도', '21시_속도', '22시_속도', '23시_속도', '24시_속도', '01시_교통량', '02시_교통량',
       '03시_교통량', '04시_교통량', '05시_교통량', '06시_교통량', '07시_교통량', '08시_교통량',
       '09시_교통량', '10시_교통량', '11시_교통량', '12시_교통량', '13시_교통량', '14시_교통량',
       '15시_교통량', '16시_교통량', '17시_교통량', '18시_교통량', '19시_교통량', '20시_교통량',
       '21시_교통량', '22시_교통량', '23시_교통량', '24시_교통량', '합류도로수', '제한속도', '01시_밀도',
       '02시_밀도', '03시_밀도', '04시_밀도', '05시_밀도', '06시_밀도', '07시_밀도', '08시_밀도',
       '09시_밀도', '10시_밀도', '11시_밀도', '12시_밀도', '13시_밀도', '14시_밀도', '15시_밀도',
       '16시_밀도', '17시_밀도', '18시_밀도', '19시_밀도', '20시_밀도', '21시_밀도', '22시_밀도',
       '23시_밀도', '24시_밀도'],
      dtype='object')

In [9]:
df = csvv[['지점번호', '방향','합류도로수','제한속도']]

In [10]:
df

      지점번호  방향  합류도로수  제한속도
0     C-19  상행      2    60
1     C-19  하행      2    60
2     D-07  상행      0    50
3     D-07  하행      0    50
4     C-17  상행      3    80
...    ...  ..    ...   ...
3073  C-17  하행      2    80
3074  C-18  상행      2    60
3075  C-18  하행      2    60
3076  C-20  상행      2    60
3077  C-20  하행      2    60

[3078 rows x 4 columns]

In [20]:
df = df.drop_duplicates()

In [21]:
df

   지점번호  방향  합류도로수  제한속도
0  C-19  상행      2    60
1  C-19  하행      2    60
2  D-07  상행      0    50
3  D-07  하행      0    50
4  C-17  상행      3    80
5  C-17  하행      2    80
6  C-18  상행      2    60
7  C-18  하행      2    60
8  C-20  상행      2    60
9  C-20  하행      2    60

In [11]:
ori_df = pd.read_csv('/content/drive/MyDrive/공모전/데이터/학습용/데이터변환1.csv')

In [17]:
ori_df['합류도로수'] = 0
ori_df['제한속도'] = 0

In [18]:
ori_df

,Unnamed: 0,시간,속도,교통량,일자,요일,도로명,지점번호,시점명,종점명,방향,거리,차선수,기능유형구분,도심/외곽구분,권역구분,합류도로수,제한속도
0,0,0,58.43,116,20220302,2,강동대로,C-19,올림픽대교북단,올림픽대교남단,상행,1228,3,주간선도로,외곽,광진구,0,0
1,1,1,57.97,92,20220302,2,강동대로,C-19,올림픽대교북단,올림픽대교남단,상행,1228,3,주간선도로,외곽,광진구,0,0
2,2,2,61.02,102,20220302,2,강동대로,C-19,올림픽대교북단,올림픽대교남단,상행,1228,3,주간선도로,외곽,광진구,0,0
3,3,3,61.25,174,20220302,2,강동대로,C-19,올림픽대교북단,올림픽대교남단,상행,1228,3,주간선도로,외곽,광진구,0,0
4,4,4,57.99,447,20220302,2,강동대로,C-19,올림픽대교북단,올림픽대교남단,상행,1228,3,주간선도로,외곽,광진구,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37435,37435,19,42.84,1125,20230131,1,천호대로,C-20,천호대교북단,천호대교남단,상행,1001,3,주간선도로,외곽,광진구,0,0
37436,37436,20,44.97,998,20230131,1,천호대로,C-20,천호대교북단,천호대교남단,상행,1001,3,주간선도로,외곽,광진구,0,0
37437,37437,21,47.14,954,20230131,1,천호대로,C-20,천호대교북단,천호대교남단,상행,1001,3,주간선도로,외곽,광진구,0,0
37438,37438,22,49.55,701,20230131,1,천호대로,C-20,천호대교북단,천호대교남단,상행,1001,3,주간선도로,외곽,광진구,0,0
37439,37439,23,51.73,496,20230131,1,천호대로,C-20,천호대교북단,천호대교남단,상행,1001,3,주간선도로,외곽,광진구,0,0

In [24]:
for i in range(0, 37440) :
  if ori_df['지점번호'][i] == 'C-19' :
    if ori_df['방향'] == '상행' :
      ori_df['합류도로수'][i] == 2, ori_df['제한속도'][i] == 60

ValueError: ignored